name: Generate and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate-stubs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install node packages
        run: npm install -g gh-all-repos
      - name: Ensure readmes directory exists
        run: mkdir -p readmes
      - name: Generate stubs
        run: scripts/get-repo-list.sh | while read repo; do [ ! -f "readmes/$repo" ] && cp ./config/empty-file.md "readmes/$repo.md"; done
      - name: Commit and push
        run: |
          git add readmes
          git diff-index --quiet HEAD -- && exit 0 # Exit if no changes
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m "Update readme stubs"
          git pull --rebase
          git push
  build:
    runs-on: ubuntu-latest
    needs: generate-stubs
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install node packages
        run: npm install -g gh-all-repos
      - name: Generate readme files
        run: scripts/do-generate.sh
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Generate index file
        run: scripts/generate-homepage.mjs
      - name: Copy config
        run: cp config/_config.yml generated/_config.yml
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./generated
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
