name: Generate Stubs

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install node packages
        run: npm install -g gh-all-repos
      - name: Ensure readmes directory exists
        run: mkdir -p readmes
      - name: Generate stubs
        run: gh-all-repos list PythonCoderAS --no-private --no-show-owner-name | while read repo; do [ ! -f "readmes/$repo" ] && cp ./config/empty-file.md "readmes/$repo.md"; done
      - name: Commit and push
        run: |
          git add readmes
          git diff-index --quiet HEAD -- && exit 0 # Exit if no changes
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m "Update readme stubs"
          git pull --rebase
          git push